foreach(layer memory api service_memory service)
    file(GLOB_RECURSE files "${ROOT}/include/${layer}/*.hpp" "${ROOT}/src/${layer}/*.cpp")
    foreach(path IN LISTS files)
        file(READ "${path}" source)
        string(REGEX MATCHALL "#include[^\n]+" includes "${source}")
        foreach(include IN LISTS includes)
            if(layer STREQUAL "memory" AND include MATCHES "\"(api|service|service_memory)/")
                message(FATAL_ERROR "Storage depends on upper layer: ${path}: ${include}")
            elseif(layer STREQUAL "api" AND include MATCHES "\"(service|service_memory)/")
                message(FATAL_ERROR "Library API depends on application policy: ${path}: ${include}")
            elseif(layer STREQUAL "service_memory" AND include MATCHES "(\"(api|service)/|<httplib.h>|<sybdb.h>|\"App.h\"|Poco/)")
                message(FATAL_ERROR "Service memory bypasses storage abstraction: ${path}: ${include}")
            elseif(layer STREQUAL "service" AND include MATCHES "\"memory/")
                message(FATAL_ERROR "Service bypasses service memory: ${path}: ${include}")
            endif()
        endforeach()
    endforeach()
endforeach()
file(READ "${ROOT}/src/service_memory/CanvasServiceMemory.cpp" canvas_memory)
if(canvas_memory MATCHES "#include[^\n]+memory/(LruMemory|RedisMemory|RedisClient)")
    message(FATAL_ERROR "CanvasServiceMemory must use MemoryClass instead of storage drivers")
endif()
file(READ "${ROOT}/src/memory/MemoryClass.cpp" generic_memory)
if(generic_memory MATCHES "canvas:|chat_room|settings-revision|_cache_generation|CPP_CANVAS")
    message(FATAL_ERROR "MemoryClass contains canvas-specific storage policy")
endif()
message(STATUS "Layer dependency checks passed")

file(READ "${ROOT}/include/Canvas.hpp" canvas_model)
if(canvas_model MATCHES "active_users|user_conn_counts|WebSocketCallbacks")
 message(FATAL_ERROR "C++ Canvas must not manage user connections")
endif()
